# Generated by Django 6.1 on 2026-09-10

from django.db import migrations, models
import config.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="nss/programme-officers/",
                validators=[config.validators.image_upload_validator],
            ),
        ),
    ]
