# Generated by Django 6.1 on 2026-08-15 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NSSUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nss_units', to='nss.college')),
                ('programme_officer', models.ForeignKey(blank=True, limit_choices_to={'role': 'PROGRAMME_OFFICER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_nss_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['college', 'unit_number'],
                'constraints': [models.UniqueConstraint(fields=('college', 'unit_number'), name='unique_unit_per_college')],
            },
        ),
    ]
