# Generated by Django 6.1 on 2026-08-27 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('hours', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nss_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='nss.nssunit')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
