# Generated by Django 6.1 on 2026-08-27 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0004_event_eventparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='nss_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='nss.nssunit'),
        ),
    ]
