# Generated by Django 6.1 on 2026-09-10

from django.db import migrations, models
import config.validators


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0005_event_nss_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="nss/activities/",
                validators=[config.validators.image_upload_validator],
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="image_file",
            field=models.ImageField(
                blank=True,
                help_text="Uploaded image. This takes precedence over the legacy image value.",
                null=True,
                upload_to="nss/events/",
                validators=[config.validators.image_upload_validator],
            ),
        ),
        migrations.AddField(
            model_name="nssunit",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="nss/units/",
                validators=[config.validators.image_upload_validator],
            ),
        ),
    ]
